### ISSUE TITLE
1회 전송 수 및 로그 보관 일수 기능 지원 요청

### ISSUE THREAD

**Issue by jinbae1** [nanny-on/agent#43]
1. 에이전트 관리 > 운영 정책 > 기본 탭 > 1회 전송 수 기능 지원 요청
2. 에이전트 관리 > 운영 정책 > 기본 탭 > 로그 보관 일수 기능 지원 요청

**Comment by jhrang** [comment]
1. 에이전트 관리 > 운영 정책 > 기본 탭 > 1회 전송 수 기능 개발 완료
 - 1회 전송 수 설정하면 해당 설정값 만큼 패킷이 전송되도록 기능 개발
2. 에이전트 관리 > 운영 정책 > 기본 탭 > 로그 보관 일수 기능 개발 완료
  - 로그 보관 일수 설정하면 해당 일수 이후에는 로그가 삭제되도록 기능 개발 완료
