### ISSUE TITLE
nannysvc 프로세스 실행 상태 감시 기능 추가  요청

### ISSUE THREAD

**Issue by he-siu** [nanny-on/agent#45]
1. nannysvc 프로세스의 실행 상태 감시(watchdog) 기능 추가 요청
 
 - 에이전트 관리 > 운영 정책 > 기본 탭 - '실행 상태 감시' 
 - 서비스가 정상 동작하지 않을 경우 강제 재시작하도록 기능 구현 요청

**Comment by jhrang** [comment]
1. nannysvc 프로세스의 실행 상태 감시(watchdog) 기능 추가 개발 완료
 - 에이전트 관리 > 운영 정책 > 기본 탭 - '실행 상태 감시'를 설정하는 경우
 서비스가 정상 동작하지 않을 경우 강제 재시작하도록 기능 구현 완료
