### ISSUE TITLE
issue :  에이전트 삭제 시 core 덤프 발생

### ISSUE THREAD

**Issue by EunmiHam** [nanny-on/agent#47]
1. 설치된 에이전트에서 삭제 스크립트 실행 후 에이전트 정지 과정에서 발생한 core 덤프가 발생하여 분석 요청

**Comment by jhrang** [comment]
1. 원인
 - 파일 update시 system 명령어로 이전 프로세스가 종료되지 않은 상태에서 파일이 강제 copy되어 발생한 문제

2. 해결 
 - 프로세스를 fork후 child 프로세스에서 execl 명령어를 사용하여 프로세스를 분리한 후 파일 copy하도록 수정
