### ISSUE TITLE
issue : 파일 정보 전송시 일부 정보가 누락되는 현상 수정 요청

### ISSUE THREAD

**Issue by ytryu12** [nanny-on/agent#49]
1. 운영 정책에서 파일 정보 수집시 일부 파일 정보가 누락되는 현상 발생

**Comment by jhrang** [comment]
1. 원인
 - Multi-Thread 환경에서 파일 정보를 전송하는 메모리가 동기화 처리가 되지 않아서 발생한 문제
2. 해결
 - 파일 정보 전송 시 메모리 동기화 처리 추가
