### ISSUE TITLE
issue : H/W 정보관리에서 CPU 정보가 표시되지 않는 문제 수정 요청

### ISSUE THREAD

**Issue by sklee-lsk** [nanny-on/agent#51]
1. 현상
 - H/W 정보관리에 리눅스 CPU이름이 표시되지 않는 문제.
 
2. 확인사항
 - 서버DB에서 host_hw에서 CPUID 값 2확인 site_cpu에서  id 2 값에 AMD Ryzen 9 3900XT 12-Core Processor 데이터 확인
 - 콘솔DB에서 site_cpu에 CPUID 값에 2가 없는 것으로 확인.
 - 서버 콘솔간 동기화 문제로 추정

**Comment by jhrang** [comment]
1. 원인
 - CPU 정보 ADD 되는 부분 처리 오류
 - Console 에서 자동 리프레쉬 되는 기능 누락
2. 해결
 - CPU 정보 ADD 되는 부분 처리 오류 수정
 - Console 에서 자동 리프레쉬 되는 기능 구현
