### ISSUE TITLE
H/W 정보관리에서 BIOS 날짜 표시 방식 변경 요청

### ISSUE THREAD

**Issue by ehyam** [nanny-on/agent#53]
1. 자산관리 -> H/W 정보 관리에서 BIOS 날짜 표시 방식을 07/02/2021 방식에서 2021-07-02와 같은 방식으로 변경 요청

**Comment by jhrang** [comment]
1. 원인
 - /sys/class/dmi/id/bios_date 파일을 조회하여 표시하는데 07/02/2017 값을 그대로 전송
2.해결
 - /sys/class/dmi/id/bios_date 파일을 조회한 데이터를 parsing하여 2021-07-02 방식으로 변환하여 전송
